# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        # Symfony\Component\Security\Core\User\User: bcrypt
        ToG\UserBundle\Entity\User: bcrypt

    provider: main

    role_hierarchy:
        # Les modérateurs du forum
        ROLE_MOD:         [ROLE_USER]
        # Les maîtres du jeu
        ROLE_GM:          [ROLE_USER]
        # Les administrateurs simples
        ROLE_ADMIN:       [ROLE_USER, ROLE_MOD, ROLE_GM]
        # Dieu
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        # in_memory:
        #     memory:
        #         users:
        #             user:  { password: 123456, roles: [ 'ROLE_USER' ] }
        #             mod:   { password: 123456, roles: [ 'ROLE_MOD' ] }
        #             gm:    { password: 123456, roles: [ 'ROLE_GM' ] }
        #             admin: { password: 123456, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity:
                class: ToG\UserBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|img|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            # provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target:     /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
