# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.bbcode:
        class: ToG\ForumBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }

    app.temp_uploader:
        class: ToG\ForumBundle\FileUploader
        arguments: ['%temp_directory%']

    app.users_avatar_uploader:
        class: ToG\ForumBundle\FileUploader
        arguments: ['%users_avatars_directory%']

    app.characters_avatar_uploader:
        class: ToG\ForumBundle\FileUploader
        arguments: ['%characters_avatars_directory%']
