register:
    path:     /inscription
    defaults: { _controller: ToGUserBundle:Registration:register }

viewprofile:
    path:     /profil-{userId}
    defaults: { _controller: ToGUserBundle:User:viewprofile }
    requirements:
        userId: '\d+'

editprofile:
    path:     /profil-{userId}/edit
    defaults: { _controller: ToGUserBundle:User:editprofile }
    requirements:
        userId: '\d+'
