register:
    path:     /register
    defaults: { _controller: ToGUserBundle:Registration:register }

viewprofile:
    path:     /user-{userId}
    defaults: { _controller: ToGUserBundle:User:viewprofile }
    requirements:
        userId: '\d+'

editprofile:
    path:     /user-{userId}/edit
    defaults: { _controller: ToGUserBundle:User:editprofile }
    requirements:
        userId: '\d+'
