createcharacter:
    path:     /creer-un-personnage
    defaults: { _controller: ToGRolePlayBundle:Character:createCharacter }

viewcharacter:
    path:     /personnage-{characterId}
    defaults: { _controller: ToGRolePlayBundle:Character:viewCharacter }
    requirements:
        characterId: '\d+'

editcharacter:
    path:     /personnage-{characterId}/edit
    defaults: { _controller: ToGRolePlayBundle:Character:editCharacter }
    requirements:
        characterId: '\d+'

update_avatar_by_ajax:
    path:     /update/avatar/ajax
    defaults: { _controller: ToGRolePlayBundle:Character:updateAvatarByAjax }

get_rp_infos_by_ajax:
    path:     /rp/infos/ajax
    defaults: { _controller: ToGRolePlayBundle:Default:getRPInfosByAjax }