<?php

namespace ToG\RolePlayBundle\Repository;

/**
 * UserGroupAssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupAssociationRepository extends \Doctrine\ORM\EntityRepository
{
}
