<?php

namespace ToG\ForumBundle\Repository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategories($id = null)
    {
        $queryBuilder = $this->createQueryBuilder('u');

        if (isset($id)) {
            $queryBuilder->where('u.id != :identifier')
                ->setParameter('identifier', $id);
        } else {
            $queryBuilder->where('u.type = 0');
        }

        return $queryBuilder->getQuery()->getResult();
    }

    /**
     * Find all forums, index them by id, then organize the result array by creating a hierarchy with subForums
     *
     * @return array the forums
     */
    public function hierarchizeForums()
    {
        $queryBuilder = $this->createQueryBuilder('forum');

        $queryBuilder
            ->from('ToGForumBundle:Forum', 'f', 'forum.id')
        ;

        $categories_and_forums = $queryBuilder->getQuery()->getResult();

        // Afin de pouvoir les afficher correctement dans la Vue, on va ranger les sous-forums dans leurs parents
        // Pour commencer, on sépare les catégories dans un array qui leur est propre
        $toUnset = [];
        $categories = [];
        foreach ($categories_and_forums as $index => $child) {
            if ($child->getParentId()) {
                $toUnset[$index] = true;

                $subForums = $categories_and_forums[$child->getParentId()]->getSubForums();
                $subForums[] = $child;

                $categories_and_forums[$child->getParentId()]->setSubForums($subForums);
            }
        }

        foreach ($toUnset as $index => $forum) {
            unset($categories_and_forums[$index]);
        }

        return $categories_and_forums;
    }
}
